application: jieba-liantian-me
runtime: python27
api_version: 1
threadsafe: true
version:  1
default_expiration: "365d"

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt
- url: /static
  static_dir: static
- url: /.*
  script: main.app

skip_files:
    - manage.py
    - README.md
    - requirements.txt
    - sitepackages/google_appengine*
    - \.storage.*
    - \.git
    - \env\.*
    - \.idea
    - (.*)\.pyc
